apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  rbac.yaml: |
    policy.csv: |
      p, admin, applications, *, *, *
      p, developer, applications, get, *, *

